-- Seed data generated by migration script

INSERT INTO sessions (id, session_code, theme_title, is_pioneer, is_active) VALUES 
('22222222-2222-2222-2222-222222222222', '2025/2026', 'Pioneer Era', true, true);

INSERT INTO executives (id, session_id, full_name, office_position, display_order, photo_url, bio_quote, whatsapp_url) VALUES 
('exec-1', '22222222-2222-2222-2222-222222222222', 'Abdulwarees', 'President', 1, 'https://res.cloudinary.com/q9jb9wvk/image/upload/v1786657210/ahwntrie9gopeloq4x0n.jpg', 'Leading the elevation of our standard across all academic and professional fronts.', 'https://wa.me/2348000000001'),
('exec-2', '22222222-2222-2222-2222-222222222222', 'Vice President', 'Vice President', 2, 'https://res.cloudinary.com/q9jb9wvk/image/upload/v1786657210/ahwntrie9gopeloq4x0n.jpg', 'Fostering academic excellence and student welfare.', 'https://wa.me/2348000000002'),
('exec-3', '22222222-2222-2222-2222-222222222222', 'General Secretary', 'General Secretary', 3, 'https://res.cloudinary.com/q9jb9wvk/image/upload/v1786657210/ahwntrie9gopeloq4x0n.jpg', 'Ensuring seamless documentation and transparent governance.', 'https://wa.me/2348000000003'),
('exec-4', '22222222-2222-2222-2222-222222222222', 'Financial Secretary', 'Financial Secretary', 4, 'https://res.cloudinary.com/q9jb9wvk/image/upload/v1786657210/ahwntrie9gopeloq4x0n.jpg', 'Managing financial integrity and prudent resource allocation.', 'https://wa.me/2348000000004'),
('exec-5', '22222222-2222-2222-2222-222222222222', 'Treasurer', 'Treasurer', 5, 'https://res.cloudinary.com/q9jb9wvk/image/upload/v1786657210/ahwntrie9gopeloq4x0n.jpg', 'Safeguarding financial assets and accounting standards.', 'https://wa.me/2348000000005'),
('exec-6', '22222222-2222-2222-2222-222222222222', 'Public Relations Officer', 'Public Relations Officer', 6, 'https://res.cloudinary.com/q9jb9wvk/image/upload/v1786657210/ahwntrie9gopeloq4x0n.jpg', 'Amplifying student voices and broadcasting association achievements.', 'https://wa.me/2348000000006'),
('exec-7', '22222222-2222-2222-2222-222222222222', 'Social Director', 'Social Director', 7, 'https://res.cloudinary.com/q9jb9wvk/image/upload/v1786657210/ahwntrie9gopeloq4x0n.jpg', 'Curating vibrant, unforgettable student experiences.', 'https://wa.me/2348000000007'),
('exec-8', '22222222-2222-2222-2222-222222222222', 'Sports Director', 'Sports Director', 8, 'https://res.cloudinary.com/q9jb9wvk/image/upload/v1786657210/ahwntrie9gopeloq4x0n.jpg', 'Promoting physical wellness, teamwork, and athletic competitions.', 'https://wa.me/2348000000008');

INSERT INTO events (id, session_id, title, event_type, event_date, flyer_banner_url, summary_text, photo_gallery, attendees_count) VALUES 
('event-1', '22222222-2222-2222-2222-222222222222', 'Official AHEFSS Merchandise Creation & Exhibition', 'Merchandise Launch', '2026-03-15', 'https://res.cloudinary.com/q9jb9wvk/image/upload/v1786657213/q0qh8oxqwjdedpg52fyy.png', 'The Elevation Era officially unveiled its customized departmental apparel line, including branded polo shirts, caps, water bottles, pens, and ceramic mugs.', ARRAY['https://res.cloudinary.com/q9jb9wvk/image/upload/v1786657213/q0qh8oxqwjdedpg52fyy.png', 'https://res.cloudinary.com/q9jb9wvk/image/upload/v1786657218/kjg0qo41mx0dz8rxwsll.png', 'https://res.cloudinary.com/q9jb9wvk/image/upload/v1786657222/ytuhcpy2fok2va8s6lr6.png', 'https://res.cloudinary.com/q9jb9wvk/image/upload/v1786657226/bi6ekj9aoygrj7q0e5nm.png', 'https://res.cloudinary.com/q9jb9wvk/image/upload/v1786657241/zdaxvlyvyosvwmdtpwlj.png', 'https://res.cloudinary.com/q9jb9wvk/image/upload/v1786657245/yvyhwz4tacysp3nsxxrn.png', 'https://res.cloudinary.com/q9jb9wvk/image/upload/v1786657269/mpeeallq4aw29xocnium.png', 'https://res.cloudinary.com/q9jb9wvk/image/upload/v1786657274/betkoouiytt6j5gdgsmh.png', 'https://res.cloudinary.com/q9jb9wvk/image/upload/v1786657284/gbmzifq0cuurbx186hmy.png', 'https://res.cloudinary.com/q9jb9wvk/image/upload/v1786657289/o30lahu478gj7auimkmy.png', 'https://res.cloudinary.com/q9jb9wvk/image/upload/v1786657292/dgesaypialtoehueowgy.jpg', 'https://res.cloudinary.com/q9jb9wvk/image/upload/v1786657296/ijjfoottpabimhgfxx7e.jpg', 'https://res.cloudinary.com/q9jb9wvk/image/upload/v1786657300/chl4yh14jqdbwb9yje0x.jpg', 'https://res.cloudinary.com/q9jb9wvk/image/upload/v1786657302/elckqxbb8fdevcejcm9p.jpg']::TEXT[], 250),
('event-2', '22222222-2222-2222-2222-222222222222', 'Pioneer Inauguration & Elevation Symposium', 'Symposium', '2025-11-10', 'https://res.cloudinary.com/q9jb9wvk/image/upload/v1786657310/imrmgxahadt1ul13gjfx.jpg', 'The historic inauguration of the inaugural Elevation Era administration, bringing together departmental faculty, lecturers, and students.', ARRAY['https://res.cloudinary.com/q9jb9wvk/image/upload/v1786657310/imrmgxahadt1ul13gjfx.jpg', 'https://res.cloudinary.com/q9jb9wvk/image/upload/v1786657210/ahwntrie9gopeloq4x0n.jpg']::TEXT[], 400);

INSERT INTO projects (id, session_id, title, cover_image_url, summary_text, photo_gallery, display_order) VALUES 
('project-1', '22222222-2222-2222-2222-222222222222', 'Departmental Digital Archival Portal & Media Hub', 'https://res.cloudinary.com/q9jb9wvk/image/upload/v1786657310/imrmgxahadt1ul13gjfx.jpg', 'A landmark digital infrastructure project designed to permanently archive departmental history, executive achievements, event photo galleries, and lecturer directories across sessions.', ARRAY['https://res.cloudinary.com/q9jb9wvk/image/upload/v1786657310/imrmgxahadt1ul13gjfx.jpg', 'https://res.cloudinary.com/q9jb9wvk/image/upload/v1786657210/ahwntrie9gopeloq4x0n.jpg']::TEXT[], 1);

INSERT INTO lecturers (id, session_id, full_name, is_hod, photo_url, display_order) VALUES 
('lec-1', '22222222-2222-2222-2222-222222222222', 'Head of Department (HOD)', true, 'https://res.cloudinary.com/q9jb9wvk/image/upload/v1786657210/ahwntrie9gopeloq4x0n.jpg', 1),
('lec-2', '22222222-2222-2222-2222-222222222222', 'Prof. O. A. Adebayo', false, NULL, 2),
('lec-3', '22222222-2222-2222-2222-222222222222', 'Dr. Mrs. C. F. Okonkwo', false, NULL, 3),
('lec-4', '22222222-2222-2222-2222-222222222222', 'Dr. K. E. Ibrahim', false, NULL, 4),
('lec-5', '22222222-2222-2222-2222-222222222222', 'Engr. T. O. Alabi', false, NULL, 5),
('lec-6', '22222222-2222-2222-2222-222222222222', 'Mrs. A. M. Bello', false, NULL, 6),
('lec-7', '22222222-2222-2222-2222-222222222222', 'Mr. S. B. Oladipo', false, NULL, 7);

INSERT INTO founders (id, full_name, photo_url, title, message) VALUES 
('11111111-1111-1111-1111-111111111111', 'Abdulwarees', 'https://res.cloudinary.com/q9jb9wvk/image/upload/v1786657210/ahwntrie9gopeloq4x0n.jpg', 'Pioneer President, The Elevation Era', 'Welcome, AHEFFSITES!
On behalf of the founding team of The Elevation Era, I am thrilled to welcome you to the official digital portal of the Association of Home Economics and Food Science Students (AHEFSS).

When this administration took office, our core mission was encapsulated in our name: to elevate the standard of our department across all fronts. Achieving this was no small task, but by God''s grace and through the unwavering support of our Head of Department, our Staff Adviser, our esteemed lecturers, a dedicated executive council, and the entire AHEFSSITE body, we were able to push boundaries and do better.

The creation of this website stems from a critical challenge we identified: a persistent gap in information regarding the association''s work. For too long, many students were unaware of the association''s active presence, let alone the impactful programs and events being organized for their growth.

We built this platform to change that narrative permanently. This platform serves three vital purposes:
1. A Living Showcase: To bring visibility to every event, workshop, and project carried out for the benefit of our students.
2. A Permanent Legacy Archive: To ensure that the history, hard work, and milestones of our association are preserved for years to come—far beyond traditional paper handover forms.
3. A Blueprint for Future Leadership: To provide incoming administrations with a clear view of what has been accomplished, setting a benchmark that inspires higher participation and even greater achievements in every new academic session.

This portal represents the bedrock of our legacy. As you explore the achievements of The Elevation Era, I hope it fills you with pride in our department and inspires you to actively engage with the association moving forward.

Welcome aboard, and keep elevating!');

