import { createBrowserClient } from '@supabase/ssr';
import { AcademicSession, ExecutiveMember, EventItem, ProjectItem, Lecturer, Founder, FullSessionData } from './types';
import {
  LOGO_URL,
  ADMIN_LOGO_URL,
  HOD_PHOTO_URL,
  PRESIDENT_SPEECH_PHOTO_URL,
  EXEC_PHOTOS,
  EVENT_MEET_EXECUTIVES,
  EVENT_HODS_CUP,
  EVENT_CLEANUP,
  EVENT_HIV_TESTING,
  EVENT_FRESHER_ORIENTATION,
  EVENT_MERCHANDISE,
  EVENT_SKILL_ACQUISITION,
  EVENT_VIRTUAL_ANCHOR,
  EVENT_VIRTUAL_WEYESDAY,
  EVENT_VIRTUAL_FINANCE_ELEVATION,
  EVENT_VIRTUAL_MENTAL_HEALTH_WEBINAR,
  EVENT_VIRTUAL_MENTAL_HEALTH_AWARENESS,
  EVENT_ORIENTATION_PROGRAM,
  PROJECT_DEPT_SIGNAGE,
  PROJECT_DIGITAL_PORTAL,
} from './assets';

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL || '';
const supabaseAnonKey = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY || process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY || '';

export const supabase = supabaseUrl && supabaseAnonKey
  ? createBrowserClient(supabaseUrl, supabaseAnonKey)
  : null;

// Initial Fallback / Seed Data for smooth client preview when Supabase is not connected
export const MOCK_FOUNDER: Founder = {
  id: '11111111-1111-1111-1111-111111111111',
  full_name: 'Abdulwarees',
  photo_url: PRESIDENT_SPEECH_PHOTO_URL,
  title: 'President, The Elevation Era',
  message: `Welcome, AHEFFSITES!\nOn behalf of the founding team of The Elevation Era, I am thrilled to welcome you to the official digital portal of the Association of Home Economics and Food Science Students (AHEFSS).\n\nWhen this administration took office, our core mission was encapsulated in our name: to elevate the standard of our department across all fronts. Achieving this was no small task, but by God's grace and through the unwavering support of our Head of Department, our Staff Adviser, our esteemed lecturers, a dedicated executive council, and the entire AHEFSSITE body, we were able to push boundaries and do better.\n\nThe creation of this website stems from a critical challenge we identified: a persistent gap in information regarding the association's work. For too long, many students were unaware of the association's active presence, let alone the impactful programs and events being organized for their growth.\n\nWe built this platform to change that narrative permanently. This platform serves three vital purposes:\n1. A Living Showcase: To bring visibility to every event, workshop, and project carried out for the benefit of our students.\n2. A Permanent Legacy Archive: To ensure that the history, hard work, and milestones of our association are preserved for years to come—far beyond traditional paper handover forms.\n3. A Blueprint for Future Leadership: To provide incoming administrations with a clear view of what has been accomplished, setting a benchmark that inspires higher participation and even greater achievements in every new academic session.\n\nThis portal represents the bedrock of our legacy. As you explore the achievements of The Elevation Era, I hope it fills you with pride in our department and inspires you to actively engage with the association moving forward.\n\nWelcome aboard, and keep elevating!`
};

export const MOCK_SESSIONS: AcademicSession[] = [
  {
    id: '22222222-2222-2222-2222-222222222222',
    session_code: '2025/2026',
    theme_title: 'The Elevation Era',
    is_pioneer: true,
    is_active: true,
    created_at: new Date().toISOString(),
  }
];

export const MOCK_EXECUTIVE_MEMBERS: Record<string, ExecutiveMember[]> = {
  '22222222-2222-2222-2222-222222222222': [
    {
      id: 'exec-1',
      session_id: '22222222-2222-2222-2222-222222222222',
      full_name: 'Abdulwarees Olaitan Abdulazeez',
      office_position: 'President',
      display_order: 1,
      photo_url: EXEC_PHOTOS.president!,
      bio_quote: 'Leading the elevation of our standard across all academic and professional fronts.',
      whatsapp_url: 'https://wa.me/2349038384360',
    },
    {
      id: 'exec-2',
      session_id: '22222222-2222-2222-2222-222222222222',
      full_name: 'Mary Oyindamola Oloruntele',
      office_position: 'Vice President',
      display_order: 2,
      photo_url: EXEC_PHOTOS.vicePresident!,
      bio_quote: 'Fostering academic excellence and student welfare.',
      whatsapp_url: 'https://wa.me/2347047151664',
    },
    {
      id: 'exec-3',
      session_id: '22222222-2222-2222-2222-222222222222',
      full_name: 'Aishat Olapeju Adigun',
      office_position: 'General Secretary',
      display_order: 3,
      photo_url: EXEC_PHOTOS.generalSecretary ?? ADMIN_LOGO_URL,
      bio_quote: 'Ensuring seamless documentation and transparent governance.',
      whatsapp_url: 'https://wa.me/2349049085215',
    },
    {
      id: 'exec-4',
      session_id: '22222222-2222-2222-2222-222222222222',
      full_name: 'Gbemisola Deborah Daniel',
      office_position: 'Assistant General Secretary',
      display_order: 4,
      photo_url: EXEC_PHOTOS.assistantGeneralSecretary ?? ADMIN_LOGO_URL,
      bio_quote: 'Supporting administrative coordination and record management.',
      whatsapp_url: 'https://wa.me/2349065271978',
    },
    {
      id: 'exec-5',
      session_id: '22222222-2222-2222-2222-222222222222',
      full_name: 'Abigeal Oluwaseun Owoyemi',
      office_position: 'Director of Finance',
      display_order: 5,
      photo_url: EXEC_PHOTOS.directorOfFinance ?? ADMIN_LOGO_URL,
      bio_quote: 'Managing financial integrity and prudent resource allocation.',
      whatsapp_url: 'https://wa.me/2347049895821',
    },
    {
      id: 'exec-6',
      session_id: '22222222-2222-2222-2222-222222222222',
      full_name: 'Zulaikho Taiye Alaya',
      office_position: 'Welfare Director',
      display_order: 6,
      photo_url: EXEC_PHOTOS.welfareSecretary ?? ADMIN_LOGO_URL,
      bio_quote: 'Championing student wellbeing, comfort, and inclusion.',
      whatsapp_url: 'https://wa.me/2349063425921',
    },
    {
      id: 'exec-7',
      session_id: '22222222-2222-2222-2222-222222222222',
      full_name: 'Blessing Ahueiza Suleiman',
      office_position: 'Public Relations Officer 1',
      display_order: 7,
      photo_url: EXEC_PHOTOS.pro ?? ADMIN_LOGO_URL,
      bio_quote: 'Amplifying student voices and broadcasting association achievements.',
      whatsapp_url: 'https://wa.me/2348145555412',
    },
    {
      id: 'exec-8',
      session_id: '22222222-2222-2222-2222-222222222222',
      full_name: 'Ugochukwu Samuel Ifechukwu',
      office_position: 'Public Relations Officer 2',
      display_order: 8,
      photo_url: EXEC_PHOTOS.pro2!,
      bio_quote: 'Amplifying student communications and departmental visibility across all digital channels.',
      whatsapp_url: 'https://wa.me/2349031786734',
    },
    {
      id: 'exec-9',
      session_id: '22222222-2222-2222-2222-222222222222',
      full_name: 'Abdulwakil Adeyemo',
      office_position: 'Sport Secretary',
      display_order: 9,
      photo_url: EXEC_PHOTOS.sportSecretary ?? ADMIN_LOGO_URL,
      bio_quote: 'Promoting physical wellness, athletic spirit, and sports competitions.',
      whatsapp_url: 'https://wa.me/2349053293652',
    },
    {
      id: 'exec-10',
      session_id: '22222222-2222-2222-2222-222222222222',
      full_name: 'Salmat Ibrahim',
      office_position: 'Social Director',
      display_order: 10,
      photo_url: EXEC_PHOTOS.socialSecretary ?? ADMIN_LOGO_URL,
      bio_quote: 'Curating vibrant, engaging, and memorable social events.',
      whatsapp_url: 'https://wa.me/2349075951276',
    },
    {
      id: 'exec-11',
      session_id: '22222222-2222-2222-2222-222222222222',
      full_name: 'Mubashiroh Muhammed-Raji',
      office_position: 'Librarian',
      display_order: 11,
      photo_url: EXEC_PHOTOS.librarian ?? ADMIN_LOGO_URL,
      bio_quote: 'Overseeing academic resources, study materials, and information access.',
      whatsapp_url: 'https://wa.me/2348081599450',
    },
  ]
};

export const MOCK_EVENTS: Record<string, EventItem[]> = {
  '22222222-2222-2222-2222-222222222222': [
    {
      id: 'event-meet-executives',
      session_id: '22222222-2222-2222-2222-222222222222',
      title: 'Meet Your Executives',
      event_type: 'Inauguration',
      event_date: '2025-11-01',
      flyer_banner_url: EVENT_MEET_EXECUTIVES.flyer,
      summary_text: 'The official unveiling of The Elevation Era executive cabinet — meet the dedicated team of leaders serving the pioneer AHEFSS administration.',
      photo_gallery: EVENT_MEET_EXECUTIVES.gallery,
      attendees_count: 300,
    },
    {
      id: 'event-fresher-orientation',
      session_id: '22222222-2222-2222-2222-222222222222',
      title: 'Fresher Orientation Programme',
      event_type: 'Orientation',
      event_date: '2025-11-10',
      flyer_banner_url: EVENT_FRESHER_ORIENTATION.flyer,
      summary_text: 'A warm welcome to incoming students, introducing them to the department, the association, and the opportunities that lie ahead.',
      photo_gallery: EVENT_FRESHER_ORIENTATION.gallery,
      attendees_count: 200,
    },
    {
      id: 'event-hiv-testing',
      session_id: '22222222-2222-2222-2222-222222222222',
      title: 'Free HIV Testing Outreach',
      event_type: 'Health Outreach',
      event_date: '2025-12-03',
      flyer_banner_url: EVENT_HIV_TESTING.flyer,
      summary_text: 'A community health initiative providing free HIV testing and health education to students and staff, reinforcing our commitment to student welfare.',
      photo_gallery: EVENT_HIV_TESTING.gallery,
      attendees_count: 150,
    },
    {
      id: 'event-virtual-mental-health-webinar',
      session_id: '22222222-2222-2222-2222-222222222222',
      title: 'Mental Health Webinar',
      event_type: 'Virtual Event',
      event_date: '2025-11-05',
      flyer_banner_url: EVENT_VIRTUAL_MENTAL_HEALTH_WEBINAR.flyer ?? ADMIN_LOGO_URL,
      summary_text: 'An online webinar addressing mental health awareness, stress management, and academic resilience for students.',
      photo_gallery: EVENT_VIRTUAL_MENTAL_HEALTH_WEBINAR.gallery,
      attendees_count: 0,
    },
    {
      id: 'event-virtual-anchor',
      session_id: '22222222-2222-2222-2222-222222222222',
      title: 'AHEFSS Anchor',
      event_type: 'Virtual Event',
      event_date: '2025-12-26',
      flyer_banner_url: EVENT_VIRTUAL_ANCHOR.flyer,
      summary_text: 'The AHEFSS Anchor virtual series — a platform for academic and professional discussions anchored by student leaders.',
      photo_gallery: EVENT_VIRTUAL_ANCHOR.gallery,
      attendees_count: 0,
    },
    {
      id: 'event-virtual-mental-health-awareness',
      session_id: '22222222-2222-2222-2222-222222222222',
      title: 'Mental Health Awareness Week',
      event_type: 'Virtual Event',
      event_date: '2026-01-11',
      flyer_banner_url: EVENT_VIRTUAL_MENTAL_HEALTH_AWARENESS.flyer,
      summary_text: 'A week-long virtual awareness campaign focused on student mental health, featuring daily content and interactive sessions.',
      photo_gallery: EVENT_VIRTUAL_MENTAL_HEALTH_AWARENESS.gallery,
      attendees_count: 0,
    },
    {
      id: 'event-hods-cup',
      session_id: '22222222-2222-2222-2222-222222222222',
      title: "AHEFSS HOD's Cup",
      event_type: 'Sports',
      event_date: '2026-01-06',
      flyer_banner_url: EVENT_HODS_CUP.flyer,
      summary_text: "The inaugural HOD's Cup — an inter-departmental sports competition fostering teamwork, healthy competition, and departmental pride.",
      photo_gallery: EVENT_HODS_CUP.gallery,
      attendees_count: 180,
    },
    {
      id: 'event-virtual-finance-elevation',
      session_id: '22222222-2222-2222-2222-222222222222',
      title: 'Finance Elevation Series',
      event_type: 'Virtual Event',
      event_date: '2025-12-02',
      flyer_banner_url: EVENT_VIRTUAL_FINANCE_ELEVATION.flyer,
      summary_text: 'A virtual financial literacy series equipping students with essential knowledge in personal finance, budgeting, and economic empowerment.',
      photo_gallery: EVENT_VIRTUAL_FINANCE_ELEVATION.gallery,
      attendees_count: 0,
    },
    {
      id: 'event-virtual-weyesday',
      session_id: '22222222-2222-2222-2222-222222222222',
      title: 'AHEFSS Weyesday',
      event_type: 'Virtual Event',
      event_date: '2026-01-07',
      flyer_banner_url: EVENT_VIRTUAL_WEYESDAY.flyer ?? ADMIN_LOGO_URL,
      summary_text: 'AHEFSS Weyesday — a recurring virtual touchpoint for association updates, spotlights, and student engagement.',
      photo_gallery: EVENT_VIRTUAL_WEYESDAY.gallery,
      attendees_count: 0,
    },
    {
      id: 'event-orientation-program',
      session_id: '22222222-2222-2222-2222-222222222222',
      title: 'Orientation Programme (100–500L)',
      event_type: 'Orientation',
      event_date: '2026-01-10',
      flyer_banner_url: EVENT_ORIENTATION_PROGRAM.flyer,
      summary_text: 'An orientation programme designed for 200–500 level students, covering academic expectations, departmental opportunities, and association activities.',
      photo_gallery: EVENT_ORIENTATION_PROGRAM.gallery,
      attendees_count: 250,
    },
    {
      id: 'event-skill-acquisition',
      session_id: '22222222-2222-2222-2222-222222222222',
      title: 'Skill Acquisition Programme',
      event_type: 'Workshop',
      event_date: '2026-07-12',
      flyer_banner_url: EVENT_SKILL_ACQUISITION.flyer,
      summary_text: 'A hands-on skill acquisition workshop empowering students with practical vocational skills to complement their academic training.',
      photo_gallery: EVENT_SKILL_ACQUISITION.gallery,
      attendees_count: 120,
    },
    {
      id: 'event-merchandise',
      session_id: '22222222-2222-2222-2222-222222222222',
      title: 'Official AHEFSS Merchandise Launch',
      event_type: 'Merchandise',
      event_date: '2026-03-15',
      flyer_banner_url: EVENT_MERCHANDISE.flyer,
      summary_text: 'The Elevation Era officially unveiled its customized departmental apparel line — branded polo shirts, caps, water bottles, pens, and ceramic mugs.',
      photo_gallery: EVENT_MERCHANDISE.gallery,
      attendees_count: 250,
    },
    {
      id: 'event-cleanup',
      session_id: '22222222-2222-2222-2222-222222222222',
      title: 'Departmental Cleanup Exercise',
      event_type: 'Community Service',
      event_date: '2025-12-28',
      flyer_banner_url: EVENT_CLEANUP.flyer,
      summary_text: 'A departmental cleanup initiative reinforcing environmental responsibility and fostering a sense of community ownership among students.',
      photo_gallery: EVENT_CLEANUP.gallery,
      attendees_count: 80,
    },
  ]
};

export const MOCK_PROJECTS: Record<string, ProjectItem[]> = {
  '22222222-2222-2222-2222-222222222222': [
    {
      id: 'project-dept-signage',
      session_id: '22222222-2222-2222-2222-222222222222',
      title: 'Departmental Signage & Identity Project',
      cover_image_url: PROJECT_DEPT_SIGNAGE.cover,
      summary_text: 'A landmark infrastructure project that gave the department a permanent visual identity — branded signage, directional boards, and department identity graphics designed and installed for lasting legacy.',
      photo_gallery: PROJECT_DEPT_SIGNAGE.gallery,
      display_order: 1,
    },
    {
      id: 'project-digital-portal',
      session_id: '22222222-2222-2222-2222-222222222222',
      title: 'Departmental Digital Archival Portal & Media Hub',
      cover_image_url: PROJECT_DIGITAL_PORTAL.cover,
      summary_text: 'A landmark digital infrastructure project designed to permanently archive departmental history, executive achievements, event photo galleries, and lecturer directories across all academic sessions. This website is that project.',
      photo_gallery: PROJECT_DIGITAL_PORTAL.gallery,
      display_order: 2,
    },
  ]
};

export const MOCK_LECTURERS: Record<string, Lecturer[]> = {
  '22222222-2222-2222-2222-222222222222': [
    {
      id: 'lec-1',
      session_id: '22222222-2222-2222-2222-222222222222',
      full_name: 'Dr. Adeshola A. Babayeju',
      is_hod: true,
      photo_url: HOD_PHOTO_URL,
      display_order: 1,
    },
    {
      id: 'lec-2',
      session_id: '22222222-2222-2222-2222-222222222222',
      full_name: 'Professor R. M. O. Kayode',
      is_hod: false,
      photo_url: null,
      display_order: 2,
    },
    {
      id: 'lec-3',
      session_id: '22222222-2222-2222-2222-222222222222',
      full_name: 'Professor Mutiat A. Balogun',
      is_hod: false,
      photo_url: null,
      display_order: 3,
    },
    {
      id: 'lec-4',
      session_id: '22222222-2222-2222-2222-222222222222',
      full_name: 'Professor Fausat L. Kolawole',
      is_hod: false,
      photo_url: null,
      display_order: 4,
    },
    {
      id: 'lec-5',
      session_id: '22222222-2222-2222-2222-222222222222',
      full_name: 'Professor Oluwafunmilola A. Abiodun',
      is_hod: false,
      photo_url: null,
      display_order: 5,
    },
    {
      id: 'lec-6',
      session_id: '22222222-2222-2222-2222-222222222222',
      full_name: 'Dr. A. O. Dauda',
      is_hod: false,
      photo_url: null,
      display_order: 6,
    },
    {
      id: 'lec-7',
      session_id: '22222222-2222-2222-2222-222222222222',
      full_name: 'Dr. Abimbola K. Arise',
      is_hod: false,
      photo_url: null,
      display_order: 7,
    },
    {
      id: 'lec-8',
      session_id: '22222222-2222-2222-2222-222222222222',
      full_name: 'Dr. Christianah T. Gbadebo',
      is_hod: false,
      photo_url: null,
      display_order: 8,
    },
    {
      id: 'lec-9',
      session_id: '22222222-2222-2222-2222-222222222222',
      full_name: 'Dr. Deborah Opaleke',
      is_hod: false,
      photo_url: null,
      display_order: 9,
    },
    {
      id: 'lec-10',
      session_id: '22222222-2222-2222-2222-222222222222',
      full_name: 'Dr. Khadijat O. Salami',
      is_hod: false,
      photo_url: null,
      display_order: 10,
    },
    {
      id: 'lec-11',
      session_id: '22222222-2222-2222-2222-222222222222',
      full_name: 'Dr. Raji',
      is_hod: false,
      photo_url: null,
      display_order: 11,
    },
    {
      id: 'lec-12',
      session_id: '22222222-2222-2222-2222-222222222222',
      full_name: 'Mrs. W. O. Johnson',
      is_hod: false,
      photo_url: null,
      display_order: 12,
    },
    {
      id: 'lec-13',
      session_id: '22222222-2222-2222-2222-222222222222',
      full_name: 'Mrs. Abdulquadri',
      is_hod: false,
      photo_url: null,
      display_order: 13,
    },
    {
      id: 'lec-14',
      session_id: '22222222-2222-2222-2222-222222222222',
      full_name: 'Mr. Kareem',
      is_hod: false,
      photo_url: null,
      display_order: 14,
    },
    {
      id: 'lec-15',
      session_id: '22222222-2222-2222-2222-222222222222',
      full_name: 'Mrs. Abdulmaleek Aisha',
      is_hod: false,
      photo_url: null,
      display_order: 15,
    },
    {
      id: 'lec-16',
      session_id: '22222222-2222-2222-2222-222222222222',
      full_name: 'Mrs. Faidat Alawode',
      is_hod: false,
      photo_url: null,
      display_order: 16,
    },
  ]
};
