import fs from 'fs';
import path from 'path';
import { MOCK_FOUNDER, MOCK_SESSIONS, MOCK_EXECUTIVE_MEMBERS, MOCK_EVENTS, MOCK_PROJECTS, MOCK_LECTURERS } from '../lib/supabase';
import * as dotenv from 'dotenv';

// Load environment variables from .env.local
dotenv.config({ path: path.join(process.cwd(), '.env.local') });

const CLOUD_NAME = process.env.NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME;
const UPLOAD_PRESET = process.env.NEXT_PUBLIC_CLOUDINARY_UPLOAD_PRESET;

if (!CLOUD_NAME || !UPLOAD_PRESET) {
  console.error("Missing Cloudinary env variables in .env.local");
  process.exit(1);
}

const uploadedCache = new Map<string, string>();

async function uploadImage(localPath: string): Promise<string> {
  if (!localPath) return '';
  if (localPath.startsWith('http')) return localPath; // Already remote

  if (uploadedCache.has(localPath)) {
    return uploadedCache.get(localPath)!;
  }

  const absolutePath = path.join(process.cwd(), 'public', localPath);
  if (!fs.existsSync(absolutePath)) {
    console.warn(`File not found: ${absolutePath}`);
    return localPath;
  }

  const fileData = fs.readFileSync(absolutePath);
  const blob = new Blob([fileData]);
  const formData = new FormData();
  formData.append('file', blob, path.basename(absolutePath));
  formData.append('upload_preset', UPLOAD_PRESET!);

  console.log(`Uploading ${localPath} to Cloudinary...`);
  
  try {
    const res = await fetch(`https://api.cloudinary.com/v1_1/${CLOUD_NAME}/image/upload`, {
      method: 'POST',
      body: formData,
    });
    
    if (!res.ok) {
      console.error(`Failed to upload ${localPath}:`, await res.text());
      return localPath;
    }
    
    const json = await res.json();
    uploadedCache.set(localPath, json.secure_url);
    console.log(`Success: ${json.secure_url}`);
    return json.secure_url;
  } catch (error) {
    console.error(`Error uploading ${localPath}:`, error);
    return localPath;
  }
}

function esc(str: string | null | undefined): string {
  if (str === null || str === undefined) return 'NULL';
  return `'${str.replace(/'/g, "''")}'`;
}

async function run() {
  console.log("Starting Migration to Cloudinary and Generating seed.sql...");
  
  // Upload and replace images in Founder
  const founderPhoto = await uploadImage(MOCK_FOUNDER.photo_url);
  
  // Upload Sessions
  const sessionData = MOCK_SESSIONS[0]; // Pioneer session
  
  // Upload Executives
  for (const exec of MOCK_EXECUTIVE_MEMBERS[sessionData.id] || []) {
    exec.photo_url = await uploadImage(exec.photo_url);
  }
  
  // Upload Events
  for (const event of MOCK_EVENTS[sessionData.id] || []) {
    event.flyer_banner_url = await uploadImage(event.flyer_banner_url);
    const newGallery = [];
    for (const p of event.photo_gallery) {
      newGallery.push(await uploadImage(p));
    }
    event.photo_gallery = newGallery;
  }
  
  // Upload Projects
  for (const project of MOCK_PROJECTS[sessionData.id] || []) {
    project.cover_image_url = await uploadImage(project.cover_image_url);
    const newGallery = [];
    for (const p of project.photo_gallery) {
      newGallery.push(await uploadImage(p));
    }
    project.photo_gallery = newGallery;
  }
  
  // Upload Lecturers
  for (const lec of MOCK_LECTURERS[sessionData.id] || []) {
    if (lec.photo_url) {
      lec.photo_url = await uploadImage(lec.photo_url);
    }
  }

  // Generate seed.sql
  let sql = `-- Seed data generated by migration script\n\n`;
  
  // INSERT SESSION
  sql += `INSERT INTO sessions (id, session_code, theme_title, is_pioneer, is_active) VALUES \n`;
  sql += `(${esc(sessionData.id)}, ${esc(sessionData.session_code)}, ${esc(sessionData.theme_title)}, ${sessionData.is_pioneer}, ${sessionData.is_active});\n\n`;
  
  // INSERT EXECUTIVES
  const execs = MOCK_EXECUTIVE_MEMBERS[sessionData.id] || [];
  if (execs.length > 0) {
    sql += `INSERT INTO executives (id, session_id, full_name, office_position, display_order, photo_url, bio_quote, whatsapp_url) VALUES \n`;
    sql += execs.map(e => `(${esc(e.id)}, ${esc(e.session_id)}, ${esc(e.full_name)}, ${esc(e.office_position)}, ${e.display_order}, ${esc(e.photo_url)}, ${esc(e.bio_quote)}, ${esc(e.whatsapp_url)})`).join(',\n') + `;\n\n`;
  }
  
  // INSERT EVENTS
  const evts = MOCK_EVENTS[sessionData.id] || [];
  if (evts.length > 0) {
    sql += `INSERT INTO events (id, session_id, title, event_type, event_date, flyer_banner_url, summary_text, photo_gallery, attendees_count) VALUES \n`;
    sql += evts.map(e => `(${esc(e.id)}, ${esc(e.session_id)}, ${esc(e.title)}, ${esc(e.event_type)}, ${esc(e.event_date)}, ${esc(e.flyer_banner_url)}, ${esc(e.summary_text)}, ARRAY[${e.photo_gallery.map(p => esc(p)).join(', ')}]::TEXT[], ${e.attendees_count})`).join(',\n') + `;\n\n`;
  }
  
  // INSERT PROJECTS
  const projs = MOCK_PROJECTS[sessionData.id] || [];
  if (projs.length > 0) {
    sql += `INSERT INTO projects (id, session_id, title, cover_image_url, summary_text, photo_gallery, display_order) VALUES \n`;
    sql += projs.map(p => `(${esc(p.id)}, ${esc(p.session_id)}, ${esc(p.title)}, ${esc(p.cover_image_url)}, ${esc(p.summary_text)}, ARRAY[${p.photo_gallery.map(g => esc(g)).join(', ')}]::TEXT[], ${p.display_order})`).join(',\n') + `;\n\n`;
  }
  
  // INSERT LECTURERS
  const lecs = MOCK_LECTURERS[sessionData.id] || [];
  if (lecs.length > 0) {
    sql += `INSERT INTO lecturers (id, session_id, full_name, is_hod, photo_url, display_order) VALUES \n`;
    sql += lecs.map(l => `(${esc(l.id)}, ${esc(l.session_id)}, ${esc(l.full_name)}, ${l.is_hod}, ${esc(l.photo_url || null)}, ${l.display_order})`).join(',\n') + `;\n\n`;
  }
  
  // INSERT FOUNDER
  sql += `INSERT INTO founders (id, full_name, photo_url, title, message) VALUES \n`;
  sql += `(${esc(MOCK_FOUNDER.id)}, ${esc(MOCK_FOUNDER.full_name)}, ${esc(founderPhoto)}, ${esc(MOCK_FOUNDER.title)}, ${esc(MOCK_FOUNDER.message)});\n\n`;
  
  const outPath = path.join(process.cwd(), 'supabase', 'seed.sql');
  fs.writeFileSync(outPath, sql, 'utf8');
  console.log(`\nseed.sql generated at: ${outPath}`);
  console.log('Migration prep complete!');
}

run();
